apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zafz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zafz
    app.kubernetes.io/part-of: ci10t-786-0072-app
  name: devfile-sample-zafz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zafz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zafz
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0072-tenant/ci10t-786-0072-app/devfile-sample-zafz@sha256:730522c4d4bac38b00e8983ee61c9ec0922d6102579931cc7fc3fb13119b50f2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
